# -*- coding: utf-8 -*-
"""Route Optimizer Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dNYGZa7k3T9aaL98KF3tJ1sXZcBClkyj
"""

!pip install osmnx folium networkx

import heapq
import math
import time
import folium
import osmnx as ox
from dataclasses import dataclass

ox.settings.log_console = False
ox.settings.use_cache = True
print("Done!")

print("Downloading Nagpur map...")
G = ox.graph_from_place("Nagpur, Maharashtra, India", network_type="drive")
G = ox.add_edge_speeds(G)
G = ox.add_edge_travel_times(G)
print(f"Done! {len(G.nodes)} nodes, {len(G.edges)} edges")

def get_successors(G, u, weight):
    for v, edges in G[u].items():
        best = min(e.get(weight, 1) for e in edges.values())
        yield v, best

def reconstruct(prev, source, target):
    path, cur = [], target
    while cur is not None:
        path.append(cur)
        cur = prev.get(cur)
    path.reverse()
    return path if (path and path[0] == source) else []

def haversine(lat1, lon1, lat2, lon2):
    R = 6_371_000
    phi1, phi2 = math.radians(lat1), math.radians(lat2)
    dphi = math.radians(lat2 - lat1)
    dlam = math.radians(lon2 - lon1)
    a = math.sin(dphi/2)**2 + math.cos(phi1)*math.cos(phi2)*math.sin(dlam/2)**2
    return R * 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))

print("Helpers ready!")

def dijkstra(G, source, target, weight="travel_time"):
    dist = {source: 0.0}
    prev = {source: None}
    visited = set()
    heap = [(0.0, source)]
    t0 = time.perf_counter()

    while heap:
        cost, u = heapq.heappop(heap)
        if u in visited:
            continue
        visited.add(u)
        if u == target:
            break
        for v, w in get_successors(G, u, weight):
            new_cost = cost + w
            if new_cost < dist.get(v, math.inf):
                dist[v] = new_cost
                prev[v] = u
                heapq.heappush(heap, (new_cost, v))

    path = reconstruct(prev, source, target)
    duration = time.perf_counter() - t0
    return path, dist.get(target, -1), len(visited), duration

print("Dijkstra ready!")

def astar(G, source, target, weight="travel_time"):
    t_lat = G.nodes[target]["y"]
    t_lon = G.nodes[target]["x"]
    max_speed_ms = 130 / 3.6

    def h(node):
        return haversine(G.nodes[node]["y"], G.nodes[node]["x"], t_lat, t_lon) / max_speed_ms

    g_score = {source: 0.0}
    prev = {source: None}
    visited = set()
    heap = [(h(source), source)]
    t0 = time.perf_counter()

    while heap:
        _, u = heapq.heappop(heap)
        if u in visited:
            continue
        visited.add(u)
        if u == target:
            break
        for v, w in get_successors(G, u, weight):
            tentative_g = g_score[u] + w
            if tentative_g < g_score.get(v, math.inf):
                g_score[v] = tentative_g
                prev[v] = u
                heapq.heappush(heap, (tentative_g + h(v), v))

    path = reconstruct(prev, source, target)
    duration = time.perf_counter() - t0
    return path, g_score.get(target, -1), len(visited), duration

print("A* ready!")

start_lat, start_lon = ox.geocode("Nagpur Railway Station, Nagpur")
end_lat, end_lon = ox.geocode("Deekshabhoomi, Nagpur")

src = ox.nearest_nodes(G, start_lon, start_lat)
tgt = ox.nearest_nodes(G, end_lon, end_lat)

print(f"Start: {src}")
print(f"End  : {tgt}")

d_path, d_cost, d_visited, d_time = dijkstra(G, src, tgt)
a_path, a_cost, a_visited, a_time = astar(G, src, tgt)

print(f"[Dijkstra] Nodes visited: {d_visited} | Cost: {d_cost/60:.1f} min | Time: {d_time*1000:.1f} ms")
print(f"[A*]       Nodes visited: {a_visited} | Cost: {a_cost/60:.1f} min | Time: {a_time*1000:.1f} ms")
print(f"\nA* visited {d_visited - a_visited} fewer nodes!")

def node_coords(n):
    return G.nodes[n]["y"], G.nodes[n]["x"]

centre = node_coords(d_path[len(d_path)//2])
m = folium.Map(location=centre, zoom_start=14, tiles="CartoDB positron")

folium.PolyLine([node_coords(n) for n in d_path],
    color="#185FA5", weight=5, tooltip="Dijkstra").add_to(m)

folium.PolyLine([node_coords(n) for n in a_path],
    color="#3B6D11", weight=4, dash_array="10", tooltip="A*").add_to(m)

folium.Marker(node_coords(src), tooltip="Start",
    icon=folium.Icon(color="red", icon="play")).add_to(m)
folium.Marker(node_coords(tgt), tooltip="End",
    icon=folium.Icon(color="green", icon="flag")).add_to(m)

m.save("route_map.html")
print("Map saved! Also showing below:")
m